<?php

include ("hrtsDatabaseConnection.php");

$fdaAppNumber = $_REQUEST['fdaAppNumber'];
$documentType = $_REQUEST['documentType'];

$search = new update_location_form();

$search->get_location_form($fdaAppNumber,$documentType);

class update_location_form{
	
	public function get_location_form($fdaAppNumber,$documentType){
		
		$hrtsConnect = new databaseConnection();
		$hrtsConnection = $hrtsConnect->hrtsDatabaseConnection();
		
		//$results = $hrtsConnection->query("SELECT * FROM `document_location` WHERE fda_application_number = '$fdaAppNumber' AND document_type = '$documentType'");
		
		$results = $hrtsConnection->prepare("SELECT * FROM `document_location` WHERE fda_application_number = :fdaAppNumber AND document_type = :documentType");
		
		$results->bindValue(':documentType', $documentType, PDO::PARAM_STR);
		$results->bindValue(':fdaAppNumber', $fdaAppNumber, PDO::PARAM_STR);
		$results->execute();

		while($row = $results->fetch(PDO::FETCH_ASSOC)){
				
				$content = "<div id=\"locateDoc\">";
            
				$content .= "<form id=\"locateDocForm\"  name=\"locateDocForm\">";
				$content .= "<table><tbody>";
				$content .= "<tr><td class=\"tdWidth\">FDA Application Number</td><td><input type=\"text\" id=\"fdaAppNumber\" name=\"fdaAppNumber\" tabindex=\"-1\" value=\"".$row["fda_application_number"]."\" readonly=\"readonly\"/></td></tr>";
				 if($row["document_type"] == "510K_A"){
					$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\" selected=\"selected\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_B"){
					$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\" selected=\"selected\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_C"){
					$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\" selected=\"selected\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_D"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\" selected=\"selected\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_E"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\" selected=\"selected\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_F"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\" selected=\"selected\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_G"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\" selected=\"selected\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_H"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\" selected=\"selected\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_I"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\" selected=\"selected\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_J"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\" selected=\"selected\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_K"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\" selected=\"selected\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "510K_L"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\" selected=\"selected\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "master_A"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\" selected=\"selected\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "master_B"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\" selected=\"selected\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_A"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\" selected=\"selected\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_B"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\" selected=\"selected\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_C"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\" selected=\"selected\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_D"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\" selected=\"selected\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_E"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\" selected=\"selected\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_F"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\" selected=\"selected\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_G"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";

					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\" selected=\"selected\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_H"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\" selected=\"selected\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_I"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\" selected=\"selected\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "PMA_J"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\" selected=\"selected\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "IDE_A"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\" selected=\"selected\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "IDE_B"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\" selected=\"selected\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "IDE_C"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\" selected=\"selected\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "IDE_D"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\" selected=\"selected\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "IDE_E"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\" selected=\"selected\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "OCERSOP_A"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\" selected=\"selected\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				elseif($row["document_type"] == "OCERSOP_B"){
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\" selected=\"selected\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				else{
				$content .= "<tr><td >Document Type</td><td>";
					$content .= "<select name=\"documentType\">";
					$content .= "<option value=\"510K_A\" selected=\"selected\"> Original 510(k) Submissions </option>";
					$content .= "<option value=\"510K_B\"> 510(k) Hold Requests </option>";
					$content .= "<option value=\"510K_C\"> 510(k) Requests for Extensions Exemptions</option>";
					$content .= "<option value=\"510K_D\"> 510(k) Additional Information Requests</option>";
					$content .= "<option value=\"510K_E\"> 510(k) Withdrawal Requests</option>";
					$content .= "<option value=\"510K_F\"> 510(k) CLIA and Unsolicited Amendments</option>";
					$content .= "<option value=\"510K_G\"> 510(k) \"X\" Files, \"BK\" Files, and \"BK/A\" Files</option>";
					$content .= "<option value=\"510K_H\"> 510(k) Modifications or Corrections</option>";
					$content .= "<option value=\"510K_I\"> 510(k) Closeout</option>";
					$content .= "<option value=\"510K_J\"> Incomplete Responses</option>";
					$content .= "<option value=\"510K_K\"> Appeals </option>";
					$content .= "<option value=\"510K_L\"> Denovo's </option>";
					$content .= "<option value=\"master_A\">Original Master Files </option>";
					$content .= "<option value=\"master_B\">Master File Amendments and Authorization Letters</option>";
					$content .= "<option value=\"PMA_A\"> PMA Shell and Modules</option>";
					$content .= "<option value=\"PMA_B\"> PMA Modules Amendments</option>";
					$content .= "<option value=\"PMA_C\"> Original PMA Applications</option>";
					$content .= "<option value=\"PMA_D\"> Amendments to Original PMA Applications</option>";
					$content .= "<option value=\"PMA_E\"> Modifying a PMA Amendment Record</option>";
					$content .= "<option value=\"PMA_F\"> PMA Application Supplements</option>";
					$content .= "<option value=\"PMA_G\"> Amendments to PMA Supplements</option>";
					$content .= "<option value=\"PMA_H\"> PMA \"BP\" Files and \"BP/S\" Files</option>";
					$content .= "<option value=\"PMA_I\"> HDE Originals and Supplements</option>";
					$content .= "<option value=\"PMA_J\"> HDE Amendments</option>";
					$content .= "<option value=\"IDE_A\"> IDE Original Submissions/EUA's/FIH's</option>";
					$content .= "<option value=\"IDE_B\"> IDE Supplement and Amendment Submissions</option>";
					$content .= "<option value=\"IDE_C\"> IDE Log Out for Originals, Supplements and Amendments</option>";
					$content .= "<option value=\"IDE_D\"> IDE Misrouted and Corrected Documents </option>";
					$content .= "<option value=\"IDE_E\"> IDE Pre-Submissions</option>";
					$content .= "<option value=\"OCERSOP_A\"> RadHealth</option>";
					$content .= "<option value=\"OCERSOP_B\"> Form 2579</option>";
					$content .= "</select></td></tr>";
				}
				if($row["status"]== "checkout"){
				$content .= "<tr><td class=\"tdWidth\">Status</td><td><select name=\"status\"><option value=\"checkout\" selected=\"selected\">Check Out</option><option value=\"checkin\">Check In</option></select></td></tr>";
				}
				elseif($row["status"]== "checkin"){
				$content .= "<tr><td class=\"tdWidth\">Status</td><td><select name=\"status\"><option value=\"checkout\">Check Out</option><option value=\"checkin\" selected=\"selected\">Check In</option></select></td></tr>";
				}
				else{
				$content .= "<tr><td class=\"tdWidth\">Status</td><td><select name=\"status\"><option value=\"checkout\" selected=\"selected\">Check Out</option><option value=\"checkin\">Check In</option></select></td></tr>";
				}
				$content .= "<tr><td class=\"tdWidth\">Assigned Internal K Number</td><td><input type=\"text\" id=\"internalK\" name=\"internalK\" tabindex=\"-1\" value=\"".$row["k_number"]."\" readonly=\"readonly\"/></td></tr>"; 
				$content .= "<tr><td class=\"tdWidth\">Shelf Location</td><td><input type=\"text\" id=\"shelfLocation\" name=\"shelfLocation\" tabindex=\"-1\" value=\"".$row["shelf_location"]."\"/></td></tr>";
				$content .= "<tr><td class=\"tdWidth\">Check Out Location</td><td><input type=\"text\" id=\"checkoutLocation\" name=\"checkoutLocation\" tabindex=\"-1\" value=\"".$row["out_location"]."\"/></td></tr>";
				$content .= "<tr><td class=\"tdWidth\">Who Checked Out</td><td><input type=\"text\" id=\"whoCheckedOut\" name=\"whoCheckedOut\" tabindex=\"-1\" value=\"".$row["out_person"]."\"/></td></tr>";
				$content .= "<tr><td class=\"tdWidth\"><label> Checked In Date </label></td><td><input type=\"text\" id=\"checkedInDate\" name=\"checkedInDate\" class=\"datepicker2\" tabindex=\"-1\" value=\"".date("m/d/Y", (strtotime($row["check_in_date"])))."\"/></td></tr>";
				$content .= "<tr><td class=\"tdWidth\"><label> Checked Out Date </label></td><td><input type=\"text\" id=\"checkedOutDate\" name=\"checkedOutDate\" class=\"datepicker2\" tabindex=\"-1\" value=\"".date("m/d/Y", (strtotime($row["check_out_date"])))."\" /></td></tr>";
				$content .= "<tr><td class=\"tdWidth\"><label> Due In Date </label></td><td><input type=\"text\" id=\"dueInDate\" name=\"dueInDate\" class=\"datepicker2\" tabindex=\"-1\" value=\"".date("m/d/Y", (strtotime($row["due_date"])))."\"/></td></tr>";
				$content .= "</tbody></table>";
				$content .= "</form>";
							
				$content .= "</div>";				
				
				
				die($content);
				
		}
			
	}
}
?>